export enum Weather {
  BLIZZARDS = 'blizzards',
  CLEAR_SKIES = 'clearSkies',
  CLOUDS = 'clouds',
  DUST_STORMS = 'dustStorms',
  FAIR_SKIES = 'fairSkies',
  FOG = 'fog',
  GALES = 'gales',
  GLOOM = 'gloom',
  HEAT_WAVES = 'heatWaves',
  HOT_SPELLS = 'hotSpells',
  RAIN = 'rain',
  SANDSTORMS = 'sandstorms',
  SHOWERS = 'showers',
  SNOW = 'snow',
  THUNDER = 'thunder',
  THUNDERSTORMS = 'thunderstorms',
  UMBRAL_STATIC = 'umbralStatic',
  UMBRAL_WIND = 'umbralWind',
  WIND = 'wind'
}
