export enum Weather {
  Blizzards = 'blizzards',
  ClearSkies = 'clearSkies',
  Clouds = 'clouds',
  DustStorms = 'dustStorms',
  FairSkies = 'fairSkies',
  Fog = 'fog',
  Gales = 'gales',
  Gloom = 'gloom',
  HeatWaves = 'heatWaves',
  HotSpells = 'hotSpells',
  Rain = 'rain',
  Sandstorms = 'sandstorms',
  Showers = 'showers',
  Snow = 'snow',
  Thunder = 'thunder',
  Thunderstorms = 'thunderstorms',
  UmbralStatic = 'umbralStatic',
  UmbralWind = 'umbralWind',
  Wind = 'wind'
}
