import * as ZONES from './consts/zones'
import * as WEATHERS from './consts/weathers'

export default {
  [ZONES.AMH_ARAENG]: [
    45, WEATHERS.FAIR_SKIES,
    60, WEATHERS.CLOUDS,
    70, WEATHERS.DUST_STORMS,
    80, WEATHERS.HEAT_WAVES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.AZYS_LLA]: [
    35, WEATHERS.FAIR_SKIES,
    70, WEATHERS.CLOUDS,
    100, WEATHERS.THUNDER
  ],
  [ZONES.CENTRAL_SHROUD]: [
    5, WEATHERS.THUNDER,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    55, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.CENTRAL_THANALAN]: [
    15, WEATHERS.DUST_STORMS,
    55, WEATHERS.CLEAR_SKIES,
    75, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLOUDS,
    95, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.COERTHAS_CENTRAL_HIGHLANDS]: [
    20, WEATHERS.BLIZZARDS,
    60, WEATHERS.SNOW,
    70, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLEAR_SKIES,
    90, WEATHERS.CLOUDS,
    100, WEATHERS.FOG
  ],
  [ZONES.COERTHAS_WESTERN_HIGHLANDS]: [
    20, WEATHERS.BLIZZARDS,
    60, WEATHERS.SNOW,
    70, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLEAR_SKIES,
    90, WEATHERS.CLOUDS,
    100, WEATHERS.FOG
  ],
  [ZONES.EAST_SHROUD]: [
    5, WEATHERS.THUNDER,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    55, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.EASTERN_LA_NOSCEA]: [
    5, WEATHERS.FOG,
    50, WEATHERS.CLEAR_SKIES,
    80, WEATHERS.FAIR_SKIES,
    90, WEATHERS.CLOUDS,
    95, WEATHERS.RAIN,
    100, WEATHERS.SHOWERS
  ],
  [ZONES.EASTERN_THANALAN]: [
    40, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    70, WEATHERS.CLOUDS,
    80, WEATHERS.FOG,
    85, WEATHERS.RAIN,
    100, WEATHERS.SHOWERS
  ],
  [ZONES.EULMORE]: [
    10, WEATHERS.GALES,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    45, WEATHERS.CLOUDS,
    85, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.EUREKA_ANEMOS]: [
    30, WEATHERS.FAIR_SKIES,
    60, WEATHERS.GALES,
    90, WEATHERS.SHOWERS,
    100, WEATHERS.SNOW
  ],
  [ZONES.EUREKA_HYDATOS]: [
    12, WEATHERS.FAIR_SKIES,
    34, WEATHERS.SHOWERS,
    56, WEATHERS.GLOOM,
    78, WEATHERS.THUNDERSTORMS,
    100, WEATHERS.SNOW
  ],
  [ZONES.EUREKA_PAGOS]: [
    10, WEATHERS.FAIR_SKIES,
    28, WEATHERS.FOG,
    46, WEATHERS.HEAT_WAVES,
    64, WEATHERS.SNOW,
    82, WEATHERS.THUNDER,
    100, WEATHERS.BLIZZARDS
  ],
  [ZONES.EUREKA_PYROS]: [
    10, WEATHERS.FAIR_SKIES,
    28, WEATHERS.HEAT_WAVES,
    46, WEATHERS.THUNDER,
    64, WEATHERS.BLIZZARDS,
    82, WEATHERS.UMBRAL_WIND,
    100, WEATHERS.SNOW
  ],
  [ZONES.GRIDANIA]: [
    5, WEATHERS.RAIN,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    55, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.IDYLLSHIRE]: [
    10, WEATHERS.CLOUDS,
    20, WEATHERS.FOG,
    30, WEATHERS.RAIN,
    40, WEATHERS.SHOWERS,
    70, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.IL_MHEG]: [
    10, WEATHERS.RAIN,
    20, WEATHERS.FOG,
    35, WEATHERS.CLOUDS,
    45, WEATHERS.THUNDERSTORMS,
    60, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.ISHGARD]: [
    60, WEATHERS.SNOW,
    70, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLEAR_SKIES,
    90, WEATHERS.CLOUDS,
    100, WEATHERS.FOG
  ],
  [ZONES.KHOLUSIA]: [
    10, WEATHERS.GALES,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    45, WEATHERS.CLOUDS,
    85, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.KUGANE]: [
    10, WEATHERS.RAIN,
    20, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    80, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.LAKELAND]: [
    20, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLOUDS,
    85, WEATHERS.FOG,
    95, WEATHERS.RAIN,
    100, WEATHERS.THUNDERSTORMS
  ],
  [ZONES.LIMSA_LOMINSA]: [
    20, WEATHERS.CLOUDS,
    50, WEATHERS.CLEAR_SKIES,
    80, WEATHERS.FAIR_SKIES,
    90, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.LOWER_LA_NOSCEA]: [
    20, WEATHERS.CLOUDS,
    50, WEATHERS.CLEAR_SKIES,
    70, WEATHERS.FAIR_SKIES,
    80, WEATHERS.WIND,
    90, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.MIDDLE_LA_NOSCEA]: [
    20, WEATHERS.CLOUDS,
    50, WEATHERS.CLEAR_SKIES,
    70, WEATHERS.FAIR_SKIES,
    80, WEATHERS.WIND,
    90, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.MIST]: [
    20, WEATHERS.CLOUDS,
    50, WEATHERS.CLEAR_SKIES,
    70, WEATHERS.FAIR_SKIES,
    80, WEATHERS.FAIR_SKIES,
    90, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.MOR_DHONA]: [
    15, WEATHERS.CLOUDS,
    30, WEATHERS.FOG,
    60, WEATHERS.GLOOM,
    75, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.NORTH_SHROUD]: [
    5, WEATHERS.FOG,
    10, WEATHERS.SHOWERS,
    25, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    70, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.NORTHERN_THANALAN]: [
    5, WEATHERS.CLEAR_SKIES,
    20, WEATHERS.FAIR_SKIES,
    50, WEATHERS.CLOUDS,
    100, WEATHERS.FOG
  ],
  [ZONES.OUTER_LA_NOSCEA]: [
    30, WEATHERS.CLEAR_SKIES,
    50, WEATHERS.FAIR_SKIES,
    70, WEATHERS.CLOUDS,
    85, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.RHALGRS_REACH]: [
    15, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    80, WEATHERS.CLOUDS,
    90, WEATHERS.FOG,
    100, WEATHERS.THUNDER
  ],
  [ZONES.SHIROGANE]: [
    10, WEATHERS.RAIN,
    20, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    80, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.SOUTH_SHROUD]: [
    5, WEATHERS.FOG,
    10, WEATHERS.THUNDERSTORMS,
    25, WEATHERS.THUNDER,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    70, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.SOUTHERN_THANALAN]: [
    20, WEATHERS.HEAT_WAVES,
    60, WEATHERS.CLEAR_SKIES,
    80, WEATHERS.FAIR_SKIES,
    90, WEATHERS.CLOUDS,
    100, WEATHERS.FOG
  ],
  [ZONES.THE_AZIM_STEPPE]: [
    5, WEATHERS.GALES,
    10, WEATHERS.WIND,
    17, WEATHERS.RAIN,
    25, WEATHERS.FOG,
    35, WEATHERS.CLOUDS,
    75, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.THE_BOZJAN_SOUTHERN_FRONT]: [
    53, WEATHERS.FAIR_SKIES,
    65, WEATHERS.RAIN,
    77, WEATHERS.WIND,
    89, WEATHERS.THUNDER,
    100, WEATHERS.DUST_STORMS
  ],
  [ZONES.THE_CHURNING_MISTS]: [
    10, WEATHERS.CLOUDS,
    20, WEATHERS.GALES,
    40, WEATHERS.UMBRAL_STATIC,
    70, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.THE_CRYSTARIUM]: [
    20, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLOUDS,
    85, WEATHERS.FOG,
    95, WEATHERS.RAIN,
    100, WEATHERS.THUNDERSTORMS
  ],
  [ZONES.THE_DIADEM]: [
    30, WEATHERS.FAIR_SKIES,
    60, WEATHERS.FOG,
    90, WEATHERS.WIND,
    100, WEATHERS.UMBRAL_WIND
  ],
  [ZONES.THE_DRAVANIAN_FORELANDS]: [
    10, WEATHERS.CLOUDS,
    20, WEATHERS.FOG,
    30, WEATHERS.THUNDER,
    40, WEATHERS.DUST_STORMS,
    70, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.THE_DRAVANIAN_HINTERLANDS]: [
    10, WEATHERS.CLOUDS,
    20, WEATHERS.FOG,
    30, WEATHERS.RAIN,
    40, WEATHERS.SHOWERS,
    70, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.THE_FRINGES]: [
    15, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    80, WEATHERS.CLOUDS,
    90, WEATHERS.FOG,
    100, WEATHERS.THUNDER
  ],
  [ZONES.THE_GOBLET]: [
    40, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLOUDS,
    95, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.THE_LAVENDER_BEDS]: [
    5, WEATHERS.CLOUDS,
    20, WEATHERS.RAIN,
    30, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    55, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLEAR_SKIES,
    100, WEATHERS.FAIR_SKIES
  ],
  [ZONES.THE_LOCHS]: [
    20, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    80, WEATHERS.CLOUDS,
    90, WEATHERS.FOG,
    100, WEATHERS.THUNDERSTORMS
  ],
  [ZONES.THE_PEAKS]: [
    10, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    75, WEATHERS.CLOUDS,
    85, WEATHERS.FOG,
    95, WEATHERS.WIND,
    100, WEATHERS.DUST_STORMS
  ],
  [ZONES.THE_RAKTIKA_GREATWOOD]: [
    10, WEATHERS.FOG,
    20, WEATHERS.RAIN,
    30, WEATHERS.UMBRAL_WIND,
    45, WEATHERS.CLEAR_SKIES,
    85, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLOUDS
  ],
  [ZONES.THE_RUBY_SEA]: [
    10, WEATHERS.THUNDER,
    20, WEATHERS.WIND,
    35, WEATHERS.CLOUDS,
    75, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.THE_SEA_OF_CLOUDS]: [
    30, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    70, WEATHERS.CLOUDS,
    80, WEATHERS.FOG,
    90, WEATHERS.WIND,
    100, WEATHERS.UMBRAL_WIND
  ],
  [ZONES.THE_TEMPEST]: [
    20, WEATHERS.CLOUDS,
    80, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ],
  [ZONES.ULDAH]: [
    40, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLOUDS,
    95, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.UPPER_LA_NOSCEA]: [
    30, WEATHERS.CLEAR_SKIES,
    50, WEATHERS.FAIR_SKIES,
    70, WEATHERS.CLOUDS,
    80, WEATHERS.FOG,
    90, WEATHERS.THUNDER,
    100, WEATHERS.THUNDERSTORMS
  ],
  [ZONES.WESTERN_LA_NOSCEA]: [
    10, WEATHERS.FOG,
    40, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    80, WEATHERS.CLOUDS,
    90, WEATHERS.WIND,
    100, WEATHERS.GALES
  ],
  [ZONES.WESTERN_THANALAN]: [
    40, WEATHERS.CLEAR_SKIES,
    60, WEATHERS.FAIR_SKIES,
    85, WEATHERS.CLOUDS,
    95, WEATHERS.FOG,
    100, WEATHERS.RAIN
  ],
  [ZONES.WOLVES_DEN_PIER]: [
    20, WEATHERS.CLOUDS,
    50, WEATHERS.CLEAR_SKIES,
    80, WEATHERS.FAIR_SKIES,
    90, WEATHERS.FOG,
    100, WEATHERS.THUNDERSTORMS
  ],
  [ZONES.YANXIA]: [
    5, WEATHERS.SHOWERS,
    15, WEATHERS.RAIN,
    25, WEATHERS.FOG,
    40, WEATHERS.CLOUDS,
    80, WEATHERS.FAIR_SKIES,
    100, WEATHERS.CLEAR_SKIES
  ]
}
