import * as REGIONS from './consts/regions'
import * as ZONES from './consts/zones'

const ZONES_PARTITION = {
  [REGIONS.EUREKA]: [
    ZONES.EUREKA_ANEMOS,
    ZONES.EUREKA_PAGOS,
    ZONES.EUREKA_PYROS,
    ZONES.EUREKA_HYDATOS
  ],
  [REGIONS.GYR_ABANIA]: [
    ZONES.RHALGRS_REACH,
    ZONES.THE_FRINGES,
    ZONES.THE_PEAKS,
    ZONES.THE_LOCHS
  ],
  [REGIONS.ISHGARD_AND_SURROUNDING_AREAS]: [
    ZONES.ISHGARD,
    ZONES.COERTHAS_CENTRAL_HIGHLANDS,
    ZONES.COERTHAS_WESTERN_HIGHLANDS,
    ZONES.THE_SEA_OF_CLOUDS,
    ZONES.AZYS_LLA,
    ZONES.IDYLLSHIRE,
    ZONES.THE_DRAVANIAN_FORELANDS,
    ZONES.THE_DRAVANIAN_HINTERLANDS,
    ZONES.THE_CHURNING_MISTS
  ],
  [REGIONS.LA_NOSCEA]: [
    ZONES.LIMSA_LOMINSA,
    ZONES.MIDDLE_LA_NOSCEA,
    ZONES.LOWER_LA_NOSCEA,
    ZONES.EASTERN_LA_NOSCEA,
    ZONES.WESTERN_LA_NOSCEA,
    ZONES.UPPER_LA_NOSCEA,
    ZONES.OUTER_LA_NOSCEA,
    ZONES.WOLVES_DEN_PIER
  ],
  [REGIONS.NORVRANDT]: [
    ZONES.THE_CRYSTARIUM,
    ZONES.EULMORE,
    ZONES.LAKELAND,
    ZONES.KHOLUSIA,
    ZONES.AMH_ARAENG,
    ZONES.IL_MHEG,
    ZONES.THE_RAKTIKA_GREATWOOD,
    ZONES.THE_TEMPEST
  ],
  [REGIONS.OTHERS]: [
    ZONES.MOR_DHONA,
    ZONES.MIST,
    ZONES.THE_LAVENDER_BEDS,
    ZONES.THE_GOBLET,
    ZONES.SHIROGANE,
    ZONES.THE_DIADEM,
    ZONES.THE_BOZJAN_SOUTHERN_FRONT
  ],
  [REGIONS.THANALAN]: [
    ZONES.ULDAH,
    ZONES.WESTERN_THANALAN,
    ZONES.CENTRAL_THANALAN,
    ZONES.EASTERN_THANALAN,
    ZONES.SOUTHERN_THANALAN,
    ZONES.NORTHERN_THANALAN
    // ZONES.GOLD_SAUCER
  ],
  [REGIONS.THE_BLACK_SHROUD]: [
    ZONES.GRIDANIA,
    ZONES.CENTRAL_SHROUD,
    ZONES.EAST_SHROUD,
    ZONES.SOUTH_SHROUD,
    ZONES.NORTH_SHROUD
  ],
  [REGIONS.THE_FAR_EAST]: [
    ZONES.KUGANE,
    ZONES.THE_RUBY_SEA,
    ZONES.YANXIA,
    ZONES.THE_AZIM_STEPPE
    // ZONES.THE_DOMAN_ENCLAVE
  ]
}

export default [
  REGIONS.LA_NOSCEA,
  REGIONS.THE_BLACK_SHROUD,
  REGIONS.THANALAN,
  REGIONS.ISHGARD_AND_SURROUNDING_AREAS,
  REGIONS.GYR_ABANIA,
  REGIONS.THE_FAR_EAST,
  REGIONS.NORVRANDT,
  REGIONS.EUREKA,
  REGIONS.OTHERS
].map((regionId) => ({
  regionId,
  query: regionId.replace(/[A-Z]/g, (word) => `_${word.toLowerCase()}`),
  zones: ZONES_PARTITION[regionId]
}))
